### ISSUE TITLE
Further development path

### ISSUE THREAD

**Issue by RESDE** [92lleo/ioBroker.solaredge#1]
first of call: great to offer this iobroker adapter to get full control over the SE production details (values and parameters (=addresses). Thanx a lot to the effords of the developer.

What ate the planned next steps to enhance to range of data pulling from the SE portal?

Could this topic be used to ask additional ibroker users what their ideas for enhancement are?

What ist link to the existing iobroker modbus  approach, where the users are tapping into the jungle of address clarirication and not all details of the SE euqipment (e.g.optimizers) could be not accessed via Modbis and rather have to pull datas from the SE portal?

**Comment by 92lleo** [comment]
Hi,
Currently, I don't have any additions planned as it does everything I need for now. Also, I don't have any further devices that I could test on.

For solaredge data via tcp modbus:
https://forum.iobroker.net/topic/6403/solaredge-adapter-photovoltaikanlage/ 
using this adapter:
https://github.com/ioBroker/ioBroker.modbus

Pros: you get realtime data (monitoring portal data is only refreshed every 15min) and as i read there is more detailed data available. 
Cons: you need to have the iobroker instance and the inverter in the same network. Also, for older models (as mine), modbus tcp is not implemented.

If there are further needs for this adapter, please comment them here or open another issue. Before, please check the api doc https://www.solaredge.com/sites/default/files/se_monitoring_api.pdf to see what's possible

**Comment by IvicaCve** [comment]
Hi just recognized your project. Looks very promising. I'm very interested into getting access to the control of the smart Energy devices (Zigbee). Since I have several of them and I would like to control them over central control (not isolated on solaredge web platform).
Over ModBus and api, there is only Access to Inverter and meter data (as far I can interpreat it).

Best regards and go ahead with the Project !

**Comment by 92lleo** [comment]
Hi @IvicaCve 
I'm only familiar with the api currently. I know that the solaredge devices support zigbee, but I can't give any other hints there. It's also not the goal of this project

**Comment by RESDE** [comment]
Hallo Leonhard,

Sorry dass ich einen Topic geöffnet habe, der Dir mehr Fragen und damit Arbeit „beschert“.
Ich hab grad entdeckt, dass Du in D bist. Ich hätte noch 1-2 kurze Fragen zu Deinem Hintergrund, warum Du diese Lösung angeboten hast? Leider bin ich hier schon rund 12 monaten in einer Sackgasse, da bei Solaredge es sehr wenig kompetenten support gibt.
Können wir bitte telefonieren? Meine Nummer lautet: 0151 54728093, unter welcher Nr kann ich Dich erreichen?
Grüsse
Reiner

**Comment by 92lleo** [comment]
Hi Reiner,

kein Problem. Ich melde mich bei dir.
Zusätzlich hab ich deine Nummer aus deinem Kommentar gelöscht, dass sie nicht öffentlich sichtbar ist.
