### ISSUE TITLE
Battery Status and other infos available?

### ISSUE THREAD

**Issue by andreaskoerber** [92lleo/ioBroker.solaredge#20]
Is there a way to retrieve the status of an attached battery (which the monitor displays) via the adapter?
Could any information on errors which the monitor displays, be retrieved?

**Comment by 92lleo** [comment]
Hi @andreaskoerber 
The adapter currently only supports the /overview path (as it's the only one I can test with my setup)
You can check all available endpoints here: https://www.solaredge.com/sites/default/files/se_monitoring_api.pdf
I'm (currently) not planning to include further endpoints, but contributions are always welcome

**Comment by 92lleo** [comment]
See #36 
https://github.com/iobroker-community-adapters/ioBroker.solaredge

Please repoen your issue there if it's still up to date
