### ISSUE TITLE
Enhancement request: Read power data

### ISSUE THREAD

**Issue by phifogg** [92lleo/ioBroker.solaredge#25]
Just got my SolarEdge installed and was looking for an adapter - glad this one exists. It is pretty basic as of now.

I guess you have seen the API docs here?
https://www.solaredge.com/sites/default/files//se_monitoring_api.pdf

Would allow much more data to be pulled from them. I would especially be interessted in current power readings to decide if there is spare power for some devices or not.

**Comment by 92lleo** [comment]
Hi, thanks for the feedback,
for starters, see #4 and #20 
For #4 some adaptions are necessarry, I just don't have the time currently

**Comment by 92lleo** [comment]
See #36 
https://github.com/iobroker-community-adapters/ioBroker.solaredge
--
Please repoen your issue there if it's still up to date
