### ISSUE TITLE
Not in ioBroker adapter list

### ISSUE THREAD

**Issue by Jumbo125** [92lleo/ioBroker.solaredge#28]
I think this work is great. Thank you for your time and love in this project!!

I'm new in the iobroker unit.... is there a reason, why i can't fouund it indise iobroker, in the adapter list?
IS the adapter up-to-date or is the project down?

thank you for your anser
best regards jumbo

**Comment by blawusel** [comment]
I have reinstalled IObroker. 
How can i reinstall the adapter..it has worked very well in the past

regards Bernd

**Comment by 92lleo** [comment]
Hi, you have to add the adapter via the custom url install method (just paste the github repo link). -> for further progress see https://github.com/ioBroker/ioBroker.repositories/pull/1153

**Comment by Jumbo125** [comment]
thanks
