### ISSUE TITLE
Please add you adapter to our repository

### ISSUE THREAD

**Issue by ioBrokerChecker** [92lleo/ioBroker.solaredge#3]
We saw your adapter and if it is ready please request that it is added to the repository. With this it becomes available for all users. Please consult https://github.com/ioBroker/ioBroker.repositories#add-a-new-adapter-to-the-latest-repository and the following sections for more details.
If you need help, contact us in the forum https://forum.iobroker.net/ or in the developer chat https://github.com/iobroker-community-adapters/info .

Thank you for your support.

- [x] think about to upgrade dependencies
- [x] add "request" package as dependecy if you use it (see testing failures)
- [ ] enter news in all languages (see translate tools in dev-best-practices in readme of this repo)
- [x] add the default values of your two config vars to native section in io-package
- [x] you set the values using default value of the created objects? this will not work and should never update the value on next run; 
- [ ] also ideally use async/await then you also do not need that kill-timer. 
- [ ] also https://github.com/92lleo/ioBroker.solaredge/blob/master/main.js#L146 will not work if the system is a bit slower ...

See https://github.com/ioBroker/ioBroker.repositories/pull/1153

**Comment by beKoer** [comment]
I´m interested in an official version

**Comment by 92lleo** [comment]
It's published, but not in the ioBroker repository I think: https://www.npmjs.com/package/iobroker.solaredge
I'll look into it

**Comment by 92lleo** [comment]
- [ ] think about to upgrade dependencies
- [x] add "request" package as dependecy if you use it (see testing failures)
- [ ] enter news in all languages (see translate tools in dev-best-practices in readme of this repo)
- [ ] add the default values of your two config vars to native section in io-package
- [ ] you set the values using default value of the created objects? this will not work and should never update the value on next run; 
- [ ] also ideally use async/await then you also do not need that kill-timer. 
- [ ] also https://github.com/92lleo/ioBroker.solaredge/blob/master/main.js#L146 will not work if the system is a bit slower ...

See https://github.com/ioBroker/ioBroker.repositories/pull/1153

**Comment by 92lleo** [comment]
See #36 
https://github.com/iobroker-community-adapters/ioBroker.solaredge
