### ISSUE TITLE
no Data

### ISSUE THREAD

**Issue by bluppdiwupp** [92lleo/ioBroker.solaredge#9]
I use your adapter Solaredge Monitoring (0.1.1) in ioBroker.
Unfortunately, I don't get any data. The objects only have the folder with my location ID.

I set up an NUC with Ubuntu. Can it be because of that?

The following entry is in the log file:

solaredge.0 2021-03-13 07:50:01.263 info (1940) Terminated (NO_ERROR): Without reason
solaredge.0 2021-03-13 07:50:01.258 info (1940) cleaned everything up...
solaredge.0 2021-03-13 07:50:01.257 info (1940) Done, stopping...
solaredge.0 2021-03-13 07:50:01.256 info (1940) Current power for 1810xxx: 990 W
solaredge.0 2021-03-13 07:50:00.562 info (1940) api key: 39NS...
solaredge.0 2021-03-13 07:50:00.562 info (1940) site id: 1810xxx
solaredge.0 2021-03-13 07:50:00.550 info (1940) start. Version 0.1.1 in /opt/iobroker/node_modules/iobroker.solaredge, node: v12.21.0, js-controller: 3.2.16

This repeats every 5 minutes. The Current Power value changes correctly.

Do you have a tip for me?

**Comment by 92lleo** [comment]
Hi,
I got multiple reports for that issue, I'm currently looking into it. It seems to be a problem with data point creation with the new js-controller. I'll keep you updated here on the progress. 
What js-controller version do you have?

**Comment by bluppdiwupp** [comment]
the version is js-controller: 3.2.16

**Comment by 92lleo** [comment]
Just do doublecheck: 
When you remove the "solaredge.0" object folder or the folder with your site id, the data points get created again but not updating it from then on? Thats the behaviour I currently get with the current js-controller setup.
Problem seems to be with the way i set the states, they are created again instead of updated. Will fix that hopefully within this week

**Comment by 92lleo** [comment]
Fixed it. Will do some more testing (at least more than for 0.1.1) and release it probably tomorrow if everything works out

**Comment by 92lleo** [comment]
Fixed in [0.2.0](https://github.com/92lleo/ioBroker.solaredge/releases/tag/0.2.0)
